edition = "2021"
fn_call_width = 60
force_explicit_abi = true
hard_tabs = false
match_block_trailing_comma = false
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
