---
name: Deploy Rust app to Shuttle

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: shuttle
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID }}
          cargo-shuttle-version: '0.48.2'
          secrets: |
            SENTRY_DSN = '${{ secrets.SENTRY_DSN }}'
            SENTRY_ENVIRONMENT = '${{ secrets.SENTRY_ENVIRONMENT }}'

            SMTP_ADDR = '${{ secrets.SMTP_ADDR }}'
            SMTP_AUTH = '${{ secrets.SMTP_AUTH }}'
